#ifndef _D2X_CIOS_INSTALLER_H_
#define _D2X_CIOS_INSTALLER_H_
#include "video.h"
#define TESTING_CODE 0
#define GUI_BACKGROUND_COLOR CONSOLE_BLACK
#define DEFAULT_FONT_BGCOLOR 0
#define DEFAULT_FONT_FGCOLOR 7
#define DEFAULT_FONT_WEIGHT 0
#define VERSION "3.1"
#endif
